version: '3.9'

services:
  redis:
    image: redislabs/redistimeseries:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build: .
    user: "appuser"  # Keep this line
    command: celery -A cronjob worker --loglevel=info
    container_name: celery_worker
    depends_on:
      - redis
    env_file:
      - .env

  celery_beat:
    build: .
    user: "appuser"  # Keep this line
    command: celery -A cronjob beat --loglevel=error
    depends_on:
      - redis
    env_file:
      - .env

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus  # Persistent local storage for Prometheus data
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - redis

  prometheus_collector:
    build:
      context: .
    container_name: prometheus_collector
    command: python3 prometheus_collector.py
    ports:
      - "5001:5000"
    depends_on:
      - redis
      - celery_worker
      - celery_beat

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/datasources/automatic.yml:/etc/grafana/provisioning/datasources/automatic.yml
      - ./config/grafana/dashboards/main.yml:/etc/grafana/provisioning/dashboards/main.yml
      - ./config/grafana/dashboards/airpollutiontracker.json:/var/lib/grafana/dashboards/airpollutiontracker.json
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - redis

volumes:
  redis_data:
  grafana_data:
  prometheus_data:
