{
 "title": "Air Pollution Tracker",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Current Carbon Monoxide Concentration (CO)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "co", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Air Quality Index (1 to 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    { "expr": "air_quality_index", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Nitrogen Dioxide Concentration (NO2)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "no2", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Ammonia Concentration (NH3)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nh3", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Ozone Concentration (O3)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "o3", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Air Pollutant Concentrations (µg/m³)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 6, "y": 8 },
   "targets": [
    { "expr": "co", "legendFormat": "__auto" },
    { "expr": "nh3", "legendFormat": "__auto" },
    { "expr": "no", "legendFormat": "__auto" },
    { "expr": "no2", "legendFormat": "__auto" },
    { "expr": "o3", "legendFormat": "__auto" },
    { "expr": "pm10", "legendFormat": "__auto" },
    { "expr": "pm2_5", "legendFormat": "__auto" },
    { "expr": "so2", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Nitrogen Monoxide Concentration (NO)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "no", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Coarse Particulate Matter Concentration (PM10)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pm10", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Fine Particles Matter Concentration (PM2.5)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pm2_5", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Sulfur dioxide Concentration (SO2)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "so2", "legendFormat": "__auto" }
   ]
  }
 ]
}